[package]
name = "ddbug_parser"
version = "0.2.0"
authors = ["Philip Craig <philipjcraig@gmail.com>"]
description = "Unified debug information parser"
repository = "https://github.com/philipc/ddbug"
keywords = ["debug", "DWARF", "PDB"]
categories = ["development-tools::debugging"]
license = "Apache-2.0/MIT"
edition = "2018"

[dependencies]
fnv = "1.0"
gimli = { git = "https://github.com/gimli-rs/gimli", rev = "f405adae0b78bc2755f8bbf146e86a1a692fc05f" }
log = "0.4"
memmap = "0.7"
moria = { git = "https://github.com/gimli-rs/moria", rev = "83e27832cd70f33ce835726d6b91f064ae0cb50f" }
object = "0.11"
typed-arena = "1.3"

[features]
default = []
